name: "Linux Build"

on: [push]

jobs:
  linux:
    name: '${{ matrix.os }}: ${{ matrix.compiler.vendor }}: ${{ matrix.variant }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
          - { vendor: gnu,  CC: gcc,   }
          - { vendor: llvm, CC: clang, }
        variant:
          - debug
          - release
          - sanitize

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: apt-get install packages
      run: sudo apt-get update -qq &&
           sudo apt-get install --no-install-recommends -y
               build-essential
               libcgif-dev
               pkg-config
               clang
               llvm

    - name: Build
      env:
        CC: ${{ matrix.compiler.CC }}
      run: |
          make -j"$(nproc)" VARIANT=${{ matrix.variant }}

    - name: Run
      run: |
          for i in test/data/*.yaml; do
            ./build/${{ matrix.variant }}/raytrace
          done
